# Generated by Django 5.1.7 on 2025-03-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('hours_used', models.FloatField(default=0)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('driving_hours', models.FloatField(default=0)),
                ('off_duty_hours', models.FloatField(default=0)),
                ('on_duty_hours', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('log_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
        ),
    ]
