# Generated by Django 5.1.7 on 2025-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='cumulative_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='reset_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='rest_break_taken',
            field=models.BooleanField(default=False),
        ),
    ]
