# Generated by Django 5.1.7 on 2025-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_dailylog_cumulative_hours_dailylog_reset_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='fueling_stop_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='stop_markers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
